language: node_js
node_js:
  - "6"

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm install
  - npm run vscode:prepublish

addons:
  code_climate:
    repo_token: 807f7c62e057c6ac6c618062fcb5f56f89d622a6f7de41d73273998b6a0606a5

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info

notifications:
  email:
    on_success: never
    on_failure: always
